### PR TITLE
add about 70 filters, mostly floating

### PR DESCRIPTION
**Pull request by RedDragonWebDesign**
Filters I've written over the last couple weeks.

You may want to double check the YouTube and Yahoo filters, since those will impact a lot of users.

    ! A new floating toolbar they added, under their main one. Shows up on the home page.
    ! http://www.youtube.com/
    youtube.com##ytd-feed-filter-chip-bar-renderer:style(position: absolute !important;)

    ! remove animation and folding up of sub-bar when scrolling down
    ! https://www.yahoo.com/entertainment/blogs/crush/michael-jackson-daughter-paris-plays-softball-203950369.html
    yahoo.com###ybar-inner-wrap:style(box-shadow: none !important;)
    yahoo.com###ybar-navigation:style(opacity: 1 !important; margin-top: 0 !important;)

### CODE REVIEW

**Comment by yourduskquibbles** [comment]
> ! A new floating toolbar they added, under their main one. Shows up on the home page.
> ! `http://www.youtube.com/`
> `youtube.com##ytd-feed-filter-chip-bar-renderer:style(position: absolute !important;)`

Are you able to give a specific page the new toolbar appears on or browser environment or maybe need to be logged in? It doesn't show up for me. I will definitely test the two sites you suggested before merging! Just based on previous experience deploying a filter without a lot of testing to the big sites that ends up breaking them is not good  ;)

**Comment by RedDragonWebDesign** [comment]
> YouTube - Are you able to give a specific page the new toolbar appears on or browser environment or maybe need to be logged in? It doesn't show up for me.

I think you just log in using any account. Once you're logged in, go to home page. I got it to work in both Chrome and Edge. I browse using Chrome, Windows 7, 1080p.

**Comment by yourduskquibbles** [comment]
> I think you just log in using any account. Once you're logged in, go to home page. I got it to work in both Chrome and Edge. I browse using Chrome, Windows 7, 1080p.

I still can't recreate this, maybe you are part of A/B site redesign testing but I will trust it is a valid filter.

**Comment by yourduskquibbles** [comment]
> ! remove animation and folding up of sub-bar when scrolling down
> ! https://www.yahoo.com/entertainment/blogs/crush/michael-jackson-daughter-paris-plays-softball-203950369.html
> yahoo.com###ybar-inner-wrap:style(box-shadow: none !important;)
> yahoo.com###ybar-navigation:style(opacity: 1 !important; margin-top: 0 !important;)

@RedDragonWebDesign Just had a chance to test this one and these work great on the example page! However just based on my experiences with yahoo are you able to add the `www.` in front of `yahoo.com` for these two filters? yahoo uses so many subdomains I like to keep exactly the domain the CSS modifying filters are developed for so it doesn't mess up other subdomains with misapplication of CSS filters.

Two other suggested additions for the example yahoo page: 
1. Can you also add `www.yahoo.com##.caas-share-buttons:style(position: unset !important; top: unset !important;)` to `floating_filters.txt` list?
2. Can you also add `yahoo.com###sda-LDRB` to the `ad_placeholders.txt` list?

Thank you in advance and once those updates are completed for the yahoo filters I will gladly accept your PR 😀

**Comment by RedDragonWebDesign** [comment]
Sure, happy to make your changes. Push complete.

**Comment by yourduskquibbles** [comment]
Thank you!

**Pull request merged**
