### PR TITLE
150 floating filters

### PR DESCRIPTION
**Pull request by RedDragonWebDesign**
Hey YDQ. He's a batch of annoyance filters I've written over the last few months. As usual, lots of floating filters.

    ! gets rid of floating thing that appears when you select text
    ! I know .t4wgMc isn't ideal, but on certain websites it's hard to find named elements to target
    google.com##.t4wgMc

image

    ! fix missing login button
    upwork.com#@#.up-btn

image
image

	! I recently discovered :has() and am making heavier use of it
	washingtonpost.com##.grey-bg:has(wp-ad)
	cnbc.com##[class^="PageBuilder-styles-select-containerFluidWidths--"]:has(#SelectRegularArticle-selectPopularOffers-1)
	cnbc.com##[class^="PageBuilder-styles-select-containerFluidWidths--"]:has(#SelectDisclosure-affiliate)
	news.yahoo.com##.caas-da:has(#sdaAdvText-INARTICLE)
	opengraph.xyz##.fixed.p-2.bg-white:has([data-feedback-fish="data-feedback-fish"])

    ! upward() can be a good trick sometimes too
    onlinelibrary.wiley.com##.publication-cover-info:upward(1):style(position: static !important;)

    ! I know .t4wgMc isn't ideal, but on certain websites it's hard to find named elements to target
	thestreet.com##.skjngj62.sksp90wl, #comments, .sko4xort.sk1t58mwx.skeey36o.sk1x4tm9s.sk6ct4gz:style(position: static !important;)
	dictionary.com##.css-1hzlfk9.eyeuakq0:style(position: static !important;)
	dictionary.com##.css-1e8sny7.e1fub8bm1:style(position: absolute !important;)
	thesaurus.com##.css-1hzlfk9.eyeuakq0:style(position: static !important;)
	thesaurus.com##.css-t5iyuy.e1n64g3r0:style(position: absolute !important;)
	dictionary.com,thesaurus.com##.css-1j44f8t.e15rv17m0
	thesaurus.com##.css-lumejv.eah4o3n0, .css-1xqhw75.e1p0sp4a3

    ! I do try to find aria labels and other human readable elements when possible
    pubmed.ncbi.nlm.nih.gov##[aria-label="Provide feedback on webpage"], .current-page-label

### CODE REVIEW

**Comment by yourduskquibbles** [comment]
@RedDragonWebDesign Thank you as always! I will go through these hopefully tomorrow and test and suggest any updates.

**Comment by yourduskquibbles** [comment]
@RedDragonWebDesign I'm trying to test the `google` filter but can't seem to trigger it, do you need to be not signed-in, specific browser or on some geographic IP? Could also be some specific A/B test on user accounts?

**Comment by RedDragonWebDesign** [comment]
I tried just now to replicate it with ad blocker off, didn't work. Could be A/B, not sure. From the screenshot, looks like it was on the main google.com web search. Original trigger environment was Windows PC, Google Chrome.

**Comment by yourduskquibbles** [comment]
> 
> 
> I tried just now to replicate it with ad blocker off, didn't work. Could be A/B, not sure. From the screenshot, looks like it was on the main google.com web search. Original trigger environment was Windows PC, Google Chrome.

It must be some A/B or staged rollout...  Google loves doing these types of things to test minor changes and see how users react and engage with them. Do you mind if we leave this one filter off until it rolls out fully? Obviously a high traffic site, so want to double and triple check so don't get flooded with issue reports if it causes some unintended breakage.

**Comment by RedDragonWebDesign** [comment]
Sure, no worries. Yeah I try to mention high traffic websites in my pull request, good to have lots of eyes on those. I also had a `news.yahoo.com` filter in there you may want to glance at.

**Comment by yourduskquibbles** [comment]
> Sure, no worries. Yeah I try to mention high traffic websites in my pull request, good to have lots of eyes on those. I also had a `news.yahoo.com` filter in there you may want to glance at.

Appreciate it, I like the documentation you provide on the tricky/risky filters helps me zero in. The `news.yahoo.com` filter looks low risk to me since it seems pretty targeted to me.


Feel free to open a separate issue as a placeholder as a reminder to watch for that google rollout

**Comment by yourduskquibbles** [comment]
Thank you!

**Pull request merged**
