### PR TITLE
approximately 100 filters, mostly floating

### PR DESCRIPTION
**Pull request by RedDragonWebDesign**
Couple of high traffic website highlights below:

````
! cookie notice
uber.com##[data-baseweb="toaster"]:has-text(third party cookies)

! Leaving most of the page floated for now. This just un-floats a <th> style bar under the video.
twitch.tv##.home-header-sticky:style(position: static !important;)

! Unbreak when you click sign in button. Links are barely visible without this fix. Confirmed that it's web annoyances ultralist causing this.
quora.com##.dialog_wrapper:style(height: 500px !important;)
quora.com##.modal_dismissible_signup_dialog .dialog_wrapper .signup_form_buttons .login_footer_links a:style(color: blue !important;)
quora.com##.__live_spinner
````

image
image

````
! I've added this before, then removed it. Adding it again, turns out the YouTube chips bar still uses this code sometimes
youtube.com##ytd-feed-filter-chip-bar-renderer:style(position: static !important;)

! a blurry right arrow that obscures some video thumbnails on the YouTube home page
youtube.com###right-arrow
````

image

### CODE REVIEW

**Comment by yourduskquibbles** [comment]
@RedDragonWebDesign Thanks! I'll review soon and merge into master if I have no questions.

**Comment by RedDragonWebDesign** [comment]
Hey @yourduskquibbles. Sorry to bug you, you must be super busy. Just wanted to check in regarding this pull request. Thanks for your time.

**Comment by yourduskquibbles** [comment]
> 
> 
> Hey @yourduskquibbles. Sorry to bug you, you must be super busy. Just wanted to check in regarding this pull request. Thanks for your time.

Hi @RedDragonWebDesign Hoping to have time to finish review on this today, sorry for the delay, lots of personal items taking my time recently!

**Comment by yourduskquibbles** [comment]
THANK YOU!  these look great just made a couple updates

**Pull request merged**
